name: Expenses Tracker Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Create .env file for CI
      run: |
        echo "JWT_SECRET_KEY=6ec7e81069304ae216cc37dc4b7bdd2be4f54be5b5488b1f35d662e2b06c28fd" > .env
        echo "DATABASE_URL=postgresql://expense_user:expense_pass@db:5432/expense_tracker_db" >> .env
        echo "TEST_DATABASE_URL=postgresql://expense_user:expense_pass@db:5432/expense_tracker_test_db" >> .env
    
    - name: Start all services
      run: |
        docker compose up --build -d
    
    - name: Run migrations
      run: |
        docker compose exec web flask db upgrade
        
    - name: Run tests
      run: |
        docker compose exec web pytest
        
    - name: Run linting
      run: |
        docker compose exec web python et-cli.py lint
        
    - name: Cleanup
      run: |
        docker compose down
